### ISSUE TITLE
[Feature Request] Support mac

### ISSUE THREAD

**Issue by matanshukry** [ChicagoFlutter/lcov-cop#2]
Just tried to run this action on a mac runner, and got an error only linux containers are supported:

```
##[error]Container action is only supported on Linux
```

**Comment by felangel** [comment]
Hi @matanshukry 👋 
Thanks for opening an issue!

Unfortunately, I believe this is a limitation of Github Container Actions 😞
Are you aware of a way to support multiple operating systems with a single Container Action?

**Comment by matanshukry** [comment]
@felangel yes and no.

While docker runners are limited, the javascript ones aren't.

From what I can tell from the repo you're simply installing `lcov` and `bc` (why bc btw?) and then running shell script.

I believe it shouldn't be too difficult to run lcov from inside a .js instead of an .sh..

WDYT?

**Comment by felangel** [comment]
@matanshukry yeah definitely we can rewrite it 👍 
I probably won't have time to do it until the weekend but if you'd like to open a PR feel free 😄

**Comment by felangel** [comment]
Hi @matanshukry 👋 
We've just finished rewriting this action under the VGVentures organization as [Very Good Coverage](https://github.com/VGVentures/very-good-coverage). This repo will be deprecated and archived shortly 👍
